<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZsvoRed\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZsvoRed/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZsvoRed.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZsvoRed\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZsvoRed\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZsvoRed',
    'container.build_id' => '3c9819f3',
    'container.build_time' => 1683208162,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZsvoRed');
